version: '3'

vars:
  BINARY_NAME: ns-tui
  BIN_DIR: ./bin
  MAIN_PATH: ./cmd/ns-tui
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the application
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -ldflags="-s -w -X main.version={{.VERSION}}" -o {{.BIN_DIR}}/{{.BINARY_NAME}} {{.MAIN_PATH}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BIN_DIR}}/{{.BINARY_NAME}}"

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - "{{.BIN_DIR}}/{{.BINARY_NAME}}"

  dev:
    desc: Run the application in development mode (rebuild on change)
    cmds:
      - go run {{.MAIN_PATH}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}
      - go clean

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  lint:
    desc: Run linter
    cmds:
      - go vet ./...

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  deps:
    desc: Download dependencies
    cmds:
      - go mod download

  install:
    desc: Install the binary to $GOPATH/bin
    deps: [build]
    cmds:
      - go install {{.MAIN_PATH}}

  release:
    desc: Build optimized release binary
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -ldflags="-s -w -X main.version={{.VERSION}}" -trimpath -o {{.BIN_DIR}}/{{.BINARY_NAME}} {{.MAIN_PATH}}

  all:
    desc: Clean, format, lint, test, and build
    cmds:
      - task: clean
      - task: fmt
      - task: lint
      - task: test
      - task: build
